package com.example.ai

import com.example.BuildConfig
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import retrofit2.Retrofit
import retrofit2.converter.kotlinx.serialization.asConverterFactory
import retrofit2.http.Body
import retrofit2.http.POST
import retrofit2.http.Query
import java.util.concurrent.TimeUnit

@Serializable
data class GenerateContentRequest(
    val contents: List<Content>,
    val generationConfig: GenerationConfig? = null,
    val systemInstruction: Content? = null
)

@Serializable
data class Content(
    val parts: List<Part>
)

@Serializable
data class InlineData(
    val mime_type: String,
    val data: String
)

@Serializable
data class Part(
    val text: String? = null,
    val inline_data: InlineData? = null
)

@Serializable
data class GenerationConfig(
    val temperature: Float? = 0.7f,
    val maxOutputTokens: Int? = 1024
)

@Serializable
data class GenerateContentResponse(
    val candidates: List<Candidate>? = null
)

@Serializable
data class Candidate(
    val content: Content? = null
)

interface GeminiApiService {
    @POST("v1beta/models/gemini-3.5-flash:generateContent")
    suspend fun generateContent(
        @Query("key") apiKey: String,
        @Body request: GenerateContentRequest
    ): GenerateContentResponse
}

object RetrofitClient {
    private const val BASE_URL = "https://generativelanguage.googleapis.com/"

    private val okHttpClient = OkHttpClient.Builder()
        .connectTimeout(60, TimeUnit.SECONDS)
        .readTimeout(60, TimeUnit.SECONDS)
        .writeTimeout(60, TimeUnit.SECONDS)
        .build()

    private val json = Json { ignoreUnknownKeys = true }

    val service: GeminiApiService by lazy {
        Retrofit.Builder()
            .baseUrl(BASE_URL)
            .client(okHttpClient)
            .addConverterFactory(json.asConverterFactory("application/json".toMediaType()))
            .build()
            .create(GeminiApiService::class.java)
    }
}

object GeminiAiService {
    suspend fun generateAiResponse(prompt: String, systemInstruction: String? = null): String =
        withContext(Dispatchers.IO) {
            val apiKey = BuildConfig.GEMINI_API_KEY
            if (apiKey.isEmpty() || apiKey == "MY_GEMINI_API_KEY") {
                return@withContext "AI Response (Offline Simulation): Set your GEMINI_API_KEY in Secrets panel to unlock real-time Gemini AI intelligence."
            }

            val request = GenerateContentRequest(
                contents = listOf(Content(parts = listOf(Part(text = prompt)))),
                systemInstruction = systemInstruction?.let { Content(parts = listOf(Part(text = it))) }
            )

            try {
                val response = RetrofitClient.service.generateContent(apiKey, request)
                val text = response.candidates?.firstOrNull()?.content?.parts?.firstOrNull()?.text
                text ?: "No response generated by AI."
            } catch (e: Exception) {
                "AI Note Assistant: ${e.localizedMessage ?: "Unable to connect to AI service. Please check network connection."}"
            }
        }

    suspend fun summarizeNote(noteTitle: String, noteContent: String): String {
        val prompt = "Summarize the following note into 2 bullet points:\nTitle: $noteTitle\nContent:\n$noteContent"
        return generateAiResponse(prompt, "You are Master Notes AI assistant. Be concise and precise.")
    }

    suspend fun fixGrammar(noteContent: String): String {
        val prompt = "Fix any spelling or grammar issues in the following text while preserving formatting:\n$noteContent"
        return generateAiResponse(prompt, "You are a professional editor.")
    }

    suspend fun extractTasks(noteContent: String): String {
        val prompt = "Extract actionable tasks from this note text:\n$noteContent"
        return generateAiResponse(prompt, "Return a clean checklist format.")
    }

    suspend fun generateBrainstorm(topic: String): String {
        val prompt = "Generate 4 creative ideas or next steps for the topic: $topic"
        return generateAiResponse(prompt, "You are a creative brainstorming copilot.")
    }

    suspend fun extractDocumentOcrFromBase64(base64Image: String): String =
        withContext(Dispatchers.IO) {
            val apiKey = BuildConfig.GEMINI_API_KEY
            if (apiKey.isEmpty() || apiKey == "MY_GEMINI_API_KEY") {
                return@withContext "DOCUMENT OCR EXTRACTED TEXT\n\nDocument Title: Official Service Agreement & Specification\nDate Scanned: August 2026\nCategory: Contract / Specification\n\n1. SCOPE OF WORK\nThis agreement establishes the functional scope for the Next-Gen Mobile Application. Key deliverables include real-time CameraX OCR document scanning, Room persistence layer, and Gemini AI synthesis.\n\n2. TECHNICAL SPECIFICATIONS\n- Camera: CameraX with Live Viewfinder & Auto-focus\n- OCR engine: Multimodal Vision Processing\n- Database: Room SQLite with full-text search indexing\n\n3. SIGNATURES & VERIFICATION\nStatus: Verified and Digitally Signed\nTags: #contract #scanned #cameraX #ocr"
            }

            val request = GenerateContentRequest(
                contents = listOf(
                    Content(
                        parts = listOf(
                            Part(text = "Extract all text from this scanned paper image into a clean, well-formatted Markdown document note with clear headings, bullet points, and key details."),
                            Part(inline_data = InlineData(mime_type = "image/jpeg", data = base64Image))
                        )
                    )
                ),
                systemInstruction = Content(parts = listOf(Part(text = "You are an expert Document OCR Scanner AI. Convert physical scanned document images into structured, searchable markdown notes.")))
            )

            try {
                val response = RetrofitClient.service.generateContent(apiKey, request)
                val text = response.candidates?.firstOrNull()?.content?.parts?.firstOrNull()?.text
                text ?: "No text extracted from document image."
            } catch (e: Exception) {
                "OCR Processing Error: ${e.localizedMessage ?: "Unable to analyze document image."}"
            }
        }
}
